import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" 
      className="overflow-x-hidden
      bg-[#021428]"
      style={{}}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  relative`}
        style={{
        }}
      >
        {children}
      </body>
    </html>
  );
}
